### ISSUE TITLE
Suggestion: Add feature to help with blueprints when engineers not yet unlocked

### ISSUE THREAD

**Issue by Gerdofal** [jixxed/ed-odyssey-materials-helper#103]
When blueprints are selected for a whishlist but engineers aren't yet unlocked, or at appropriate rank, the wishlist page displays this:

![image](https://user-images.githubusercontent.com/6471848/204065449-6e59b07b-cf34-431f-ae9f-80d704c3b737.png)

I would suggest expanding upon the "Not available" box by adding a section "additional engineers needed" and suggesting which engineers to unlock... and perhaps, which are fastest to unlock if some of them are only awaiting initial contact or need ranking up.

**Comment by jixxed** [comment]
Engineers are considered within a 10kLy radius to separate the bubble and colonia. If you unlocked the colonia engineers, you can pin the blueprints. To see which engineers are crafting the blueprint you can click on the blueprint and select the desired grade. 
![image](https://user-images.githubusercontent.com/14129491/204080764-2ad5ad46-0e75-4f61-8c07-6d1c41970e40.png)

The shortest path doesn't care about the current rank, only whether the engineer has been unlocked. It assumes the commander will rank it up through crafting or take care of it themselves.
There is no clear "most efficient path" to unlocking engineers, also because the required information for that is not readily available. The app is also not intended to steer commanders into a certain direction, just to provide information so the commander can define his/her own path.
