### ISSUE TITLE
Application error on startup

### ISSUE THREAD

**Issue by AMWild** [jixxed/ed-odyssey-materials-helper#116]
On startup, after checking for a new version, I get the following error every time I attempt to start the application:

java.lang.runtimeexception: com.fasterxml.jackson.core.jsonparseexception: Illegal character((ctrl-char, code 0)): Only regular white space (\r, \n, \t) is allowed between tokens
at [source: (string)""; line: 1, column: 2]
at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.parser.fileprocessor.processstatusfile(unknown source)...

![image](https://user-images.githubusercontent.com/21271681/205849761-91c19c5d-4254-498a-be74-7f1622cfb3b1.png)

The application does not start afterwards.

I have tried uninstalling and reinstalling with no success.

**Comment by jixxed** [comment]
This is caused by a corruption in the game's status file. There is already a fix for the next release to ignore the status file if this happens. As a workaround you can start a game, that should rewrite the status file. The app will then launch normally. If you haven't launched the game yet, can you share the status file? You can find it in C:\Users[YOUR USERNAME]\Saved Games\Frontier Developments\Elite Dangerous

**Comment by AMWild** [comment]
This happened after a system crash, and I have restarted the game since then, so I probably have nothing to share now.

Thanks for the quick response.
