### ISSUE TITLE
Material Tradedown possibility

### ISSUE THREAD

**Issue by OzDruiD** [jixxed/ed-odyssey-materials-helper#127]
Hi,
The enhancements and commitment to this project continues to impress me and I was thinking bout things that could really make this my one stop shop over other competing ship build tools and one item that REALLY would be cool is the ability for the tool to make 'trade down' recommendations.

Eg.  You have 300  Bananas - but your  Carrot Cake needs 50 Carrots, so the tool recommends you can "afford" to trade down 250 bananas to the 50 carrots you need -  but is ALSO 'aware' that your also making a banana cake - and it needs 50  - so your still ok for current Bananas - but if you thern go Whoops - I need 2 Banana cakes - and "add" another Banana cake recipe - that dynamically changes how either it recommends something other than bananans (as you need extra Bananas)  or a combination of Bananas and something else - or just warns you that you cannot make the Carrot cake anymore.

I assume thats a LOT of code, a LOT of blueprint indexing or similar thoughts,  but its one off the key features of another tool that really is amazing.    Thank you for the cconsideration - its not an Issue - more of future enhancement.

**Comment by AuroralDestiny** [comment]
Echoing this! 

If we had the material trader helper stuff that shows how much you can afford to trade things around for a current wishlisted build... I'd be the happiest shmuck alive! Adding something like this would make me never have to use another ship tool which is currently a bit outdated. I literally only use it for certain things now entirely because I need that material trader assistance in order to do things efficiently. This is probably the one addition to the app that would perfect it, in my opinion.

**Comment by jixxed** [comment]
like the idea

**Comment by OzDruiD** [comment]
Yeah its a key factor in some other tools out there thaat really lets youy min\max your resources, but I guess might take a lot of work to work out the logic and flow being "aware" of all the possibilities.  I guess once you code the "trade down costs" to a material, and you already have the BPs required material data and the user inventory - known in the tool already - hmmm a few ways to delve into it I guess, any "active" wishlists or selected active wishlists would factor in it etc.   Could be complex.

**Comment by jixxed** [comment]
limited implementation on the tooltips have been added. does not consider the wishlist.

**Comment by inventedstick** [comment]
Are you planning on adding cross trading and up trading ?

**Comment by jixxed** [comment]
I have no idea yet on how to implement this in a decent way. Although cross and up trading are not recommended ways to get your materials due to the heavy loss in materials.

**Comment by OzDruiD** [comment]
Still, liking what you have tried so far++++ for the effort.

**Comment by mrvander18** [comment]
I am a plus one for this request. 

This is a key feature of ED Engineer and I doubt I'm going to use two programs that _mostly_ do the same thing. I like the interface and look of this app but I likely won't switch over until this feature is implemented. Similar to this program, ED Engineer knows what blueprints you are "shopping" for and what materials you have. It makes recommendations for trading easy by highlighting what materials you don't have enough of but that you do have enough to trade for. It even shows suggestions of what to trade based on the percentage of the material you are trading away (i.e. 3% of your Imperial Shielding or 55% of your Biotech Conductors). Those percentages are calculated after subtracting the materials you already need for the blueprints you are "shopping" for.

I also suggest not dismissing this request purely based on what is or what is not a "recommended way to play". Trading is perfectly viable as there are Material Traders purpose built for this very thing and certain materials are easier to gather than others (i.e., Imperial Shielding vs Pharmaceutical Isolators).

**Comment by jixxed** [comment]
If someone can write up the desired behavior in **detail**, I can program it in. And this request was not dismissed, just shelved, otherwise I would have closed it already. 
I write the app in a way that it does not try to steer the player in playing a certain way, but when giving advice it better be good advice. I rather build something that makes it easier for players to collect the materials than giving bad trading advice.

**Comment by jixxed** [comment]
A very nice and detailed write up, but we are getting a bit sidetracked on other topics. 

- Capitalizing words is something that is anywhere in the app and not something I like to use as a style for the app.
- Color coding across both wishlist tabs is something I am relatively happy with at the moment and a complex topic in and of itself. I'm willing to discuss it, but that would be apart from this issue.

For this issue we need to focus on:
- only horizons materials, not commodities or odyssey stuff
- what is the logic behind the suggestions given
- behavior on wishlist/all wishlists
- coloring of horizons materials/popup can be discussed, since it only supports green/red. commodities support yellow for FC stock.

### logic
I like the idea to limit it to 3 suggestions and show percentages. The logic for what gets suggested might be:
- Same category, higher tier (downtrade)
  - Highest to lowest, no tiers below
- Other category, cross trade, max tier (crosstrade)
  - these are the materials that get collected
  - select material based on highest to lowest percentage
  - on equal percentage, select on least "used in blueprint" count
- Other category, cross trade, below max tier until same tier (crosstrade) 
  - Highest to lowest
- Uptrade

How do we deal with multiple suggestions? Right now every material is by itself. Should one suggestion affect the next one on a wishlist level or should it remain on an individual material level? Should there even be a trade calculation for the entire wishlist?(complex)

I don't like to make suggestions based on how hard something is to collect. That would be steering the player. There could potentially be an option for players to add exclusions, but you already get 3 suggestions, so it might be overkill.

### behavior 
there is a combined wishlist that behaves the same as an individual wishlist, but readonly. calculating over all the wishlists is automatically done here and the calculation should therefore remain on a wishlist level preferably. 
I like the idea of a notification.
I don't like to add settings on a wishlist level. Hide completed is also a global setting. Representation is kept simple that way.
The popup is a generic one for materials/commodities/wishlist tabs. I like to keep the downtrade info for the materials tab, so the wishlist can get it's own popup.

### color
Turning the material yellow when there are trade options will probably mean most of the materials will be yellow for most of the players. not sure how I feel about it, but not against the idea. A setting might come in to play here to toggle trade suggestions

Coloring on the trade suggestions is also a nice idea. green for down, yellow for cross and red for up.

**Comment by mrvander18** [comment]
So let's consider what the end goal is here using a high concept statement. Users have asked for the program to _calculate the most efficient trades, based on the least percentage of material traded, so a user can see, at a glance, when a blueprint can be crafted with materials on hand considering potential trades._

So there are two large categories to consider: the back-end calculation and the UX.

Let's talk about the back-end calculations. I feel percentages are the best method to present to the player as it's pure math and is not making any determination about rarity or ease of obtaining. Based on your comments, it looks like you agree with that. I think if the back-end calculations can be worked out, the UX is a separate conversation and will fall into place shortly thereafter (the design, not the programming.)

So, before I continue, is this the best place to have these discussions or would you prefer I join the Discord server to work these things out and bounce ideas around? Then we can just use the issue here to record decisions made?

**Comment by jixxed** [comment]
yes discord is a good place to discuss, might get some more people involved too.

**Comment by jixxed** [comment]
Trade suggestions have been implemented. Any further suggestions can be made and discussed on discord.
