### ISSUE TITLE
Another "Child Process exited with code 1" issue

### ISSUE THREAD

**Issue by DaggaRoosta** [jixxed/ed-odyssey-materials-helper#129]
While churning through a particularly dim SDP grind EDOMH stopped working. When I alt-tabbed out of the game I saw the "Child Process exited with code 1" alert. Restarting it, the app churned my CPU to 98% for a few minutes and then froze, looking like the picture below; if I clicked on a tab, it would be unresponsive for several seconds before disappearing and showing the "Child Process exited with code 1" alert again. This behavior is consistent now, whether in or out of the game.

Also tried the following:
restarting the game
restarting the computer
reinstalling EDOMH
No luck, same behavior.

In the bottom part of the window EDOMH says "No Odyssey journals found" but there are journal files in that location. The most recent file is a fairly large one, slightly over 3Mb. There's also an error log in the EDOMH folder which describes an EXCEPTION_ACCESS_VIOLATION. I can attach either on request. 

![edomh_bug](https://user-images.githubusercontent.com/15524620/218004149-3e8f61e5-2e84-4ba5-874c-aa22f194ed2e.png)

**Comment by DaggaRoosta** [comment]
Fixed the issue by renaming the most recent game log (adding ".old" to the end) and restarting the app. It worked again, initially with outdated info but it updated once I logged back into the game. Attached the offending game log if you're interested.
[Journal.2023-02-09T192802.01.log](https://github.com/jixxed/ed-odyssey-materials-helper/files/10704623/Journal.2023-02-09T192802.01.log)

**Comment by jixxed** [comment]
can you attach the error log if you still have it? Good you got it fixed. I see nothing wrong with the journal at first glance, so I'll check it out.

**Comment by jixxed** [comment]
Looks like the issue was caused by the many many relogs, each giving new engineerprogress entries that all got processed. these messages are very heavy on the memory and when the limit hits the app will go into garbage collection. it's constantly doing this resulting in very high CPU usage. the app is limited to 1GB + some extras. unlimited the journal used up almost 5GB ram. adding an optimization to reduce the number of engineerprogress processed, since we only need the ones after the latest relog. The supplied journal loads without issue with this fix applied.

**Comment by DaggaRoosta** [comment]
LOL, the engineering grind is so absurd. You shouldn't have to be dealing with these weird edge cases. I figured the grindy user behavior was likely a contributing factor, and sure enough.

Thank you for looking into it, and thank you for the excellent software! I suspect I would have quit the game altogether without it.
