### ISSUE TITLE
use green/red progress style bars to show progress on wishlist required materials

### ISSUE THREAD

**Issue by slippycheeze** [jixxed/ed-odyssey-materials-helper#135]
the "Required materials" section of the wishlist for both odyssey and horizons materials shows them with the number required, and available.   on mouseover it flips to show the number remaining to farm.

I'd love to see, instead, a progress-style bar like is used for horizons on the "Materials" tab; this not very good mockup hopefully gives the general idea:
![image](https://user-images.githubusercontent.com/306753/221570790-b3dacd44-496f-44af-86da-288bc6734c1c.png)

I suspect that moving the "Required 58" to the top line, eastmost, and only having the progress bar would work well, but honestly, anything in the general region would probably work for me.
![image](https://user-images.githubusercontent.com/306753/221571688-14cbd08c-377c-4f9f-be72-19d00ef53bf1.png)

The concrete things I want to get from this change are:
1. seeing how many items remain to be farmed without having to interact with EDOMH
2. getting a sense of progress at a glance, without needing to math

If the wishlist required materials list showed "remaining" instead of "available" by default that'd be a step to the better, but it wouldn't give me the same sense of "how close" that the progress bar would.

**Comment by jixxed** [comment]
Added a simple progressbar in 2.20, this should cover most of the "concerns". 
some considerations for this implementation:
- there is no space next to the name
- not putting Remaining as a default view to keep it in sync with the filled materials. those would then need to all show 0 which is pointless.

The progressbar should give a better indication of the progress and a mouseover is not a very big interaction to not have to do math. Not that math is needed anyway since you need to collect until it becomes green :)
