### ISSUE TITLE
Failed to launch JVM

### ISSUE THREAD

**Issue by befelton** [jixxed/ed-odyssey-materials-helper#148]
Every time I hear of an update to this program, I install it and give it a try. In the past it has usually failed silently, moments after its screen appears. I  was excited to see that version 2.23 consistently throws an error message: First the failed JVM launch, then, when that is acknowledged, 'Child process exited with code 1.' This feels like progress. Does it provide any clues as to what is going on? This was from a Windows 10 machine, installed with the .msi file. In the past I tried the portable versions too, but always got the same result.

**Comment by jixxed** [comment]
You don't need to install updates manually, it is done automatically with the launcher(pacman). The error you get is caused by the app already running. you can check task manager to kill existing processes of the app. The app should close all running threads on exit, so this problem should not occur. In the past a thread could get stuck, keeping the app alive in the background. If you are running on the latest version (see About section for current version) and this problem keeps occurring, let me know anything surrounding the use of the app so I can try to reproduce. Think about: having the app running on another user account on the pc, returning PC from sleep/standby, connected to trade in the app, using it over the network, etc etc. Normal use shouldn't cause this issue so I would need to know the edgecase for when this does occur.

**Comment by befelton** [comment]
Sorry, my poor choice of words seem to have given the wrong impression. I have never gotten the program to work for any length of time. Typically I install it, it starts up, shows its screen for a second or so, then silently exits. I then give up and uninstall it.
Some time later, hearing that there has been another update, I try installing it again: hoping that whatever has prevented it from working for me in the past will have been fixed: but until this version, I always got the same result.
This version acts the same as the previous ones, in that it only works for a second two before exiting, but it is now failing with an error message, rather than silently: so I was hopeful that the message might provide a clue as to the problem.

**Comment by jixxed** [comment]
that is some strange behavior. 
perhaps anything of use is logged to: %localappdata%\Elite Dangerous Odyssey Materials Helper Launcher\log
if not, you can try backing up and removing the app config folder: %localappdata%\odyssey-materials-helper
that should give a clean run, if that works, send the folder to me.

**Comment by befelton** [comment]
The log file didn't seem to have anything useful. Removing the odyssey-materials-helper folder did the trick: the program works find now. Here's the broken one:

[odyssey-materials-helper.zip](https://github.com/jixxed/ed-odyssey-materials-helper/files/11435657/odyssey-materials-helper.zip)
