### ISSUE TITLE
Frontier API Intergration on Linux.

### ISSUE THREAD

**Issue by Freejack01** [jixxed/ed-odyssey-materials-helper#191]
I have tried several times to get integration to work and it will not. I click the button connect and it opens the browser to Frontier for auth.

After entering the login and clicking login it just sits on that page and does nothing. I have connected the API to several other programs  and it works fine with them.

NOt sure how to troubleshoot this.

**Comment by jixxed** [comment]
normally the browser pops up asking you to open something with the app, so it might be related to your browser if it doesn't.

**Comment by jixxed** [comment]
this app is not other apps, so that is not relevant. are you on Windows or Linux?

**Comment by Freejack01** [comment]
I did say Linux. Your correct this app is not other apps, which means since they work with this browser get the api auth then something is not correct in this app on Linux. I know it works on windows with no issues.

**Comment by jixxed** [comment]
other apps work by running a webserver on your local machine which make things work inside a browser. This app has it's own url scheme which is handled by the app. Unofficially the app only supports Ubuntu, since I can't go around testing every single distro.
You are probably on Arch, since more users have reported issues with it. Arch does not register the url scheme like the other distro's. Other users have been able to fix this by following these 2 steps:
The path in the .desktop file doesn't like escaping spaces in the executable's name use single-quotes for the file name instead ~/.local/share/applications/edomh.desktop
Remake the mime cache by running the command: update-mime-database ~/.local/share/mime

If you are not on Arch, you can try it all the same. 
If you want to generate a url to test with, you can copy a wishlist or loadout to clipboard and paste it in the browser address bar.

**Comment by Freejack01** [comment]
I am not on Arch I use Linux Mint which is a Ubuntu based.

**Comment by dvdmuckle** [comment]
Necroing this issue to provide a fix, registering EDOMH creates a .desktop file in your ~/.local/share/applications folder with the `MimeType` field filled out. However, xdg (I think) may not be aware of this. Try doing `cd ~/.local/share/applications && update-desktop-database .`. This works at the very least on Fedora 39, your mileage may vary on other distros, however after a bit of research I think this will work on more than Fedora.
