### ISSUE TITLE
Shortest path doesn't consider all engineer expertises 

### ISSUE THREAD

**Issue by michelvaleferreira** [jixxed/ed-odyssey-materials-helper#331]
check the blueprints and experimentals in this list. The first engineer can do a lot more than it is listed under her expertises. I'd expect to do shield booster, engine, fsd and powerplant experimentals at her facility

![Screenshot_20240612_214812](https://github.com/jixxed/ed-odyssey-materials-helper/assets/169490489/f1453708-9996-4634-ae3d-10be23aff64e)
![Screenshot_20240612_214842](https://github.com/jixxed/ed-odyssey-materials-helper/assets/169490489/8a45c57a-f317-40b5-8b4f-acb7a4e13485)
![Screenshot_20240612_214919](https://github.com/jixxed/ed-odyssey-materials-helper/assets/169490489/fba619f9-b4f2-42ac-bf49-d0669c80c768)

**Comment by jixxed** [comment]
blueprints and effects are paired since you can't apply effects without applying the blueprint first. The app assumes these belong together. It will not split the blueprint over multiple engineers. It also tries to apply as many blueprint as possible to a single engineer, so the shieldbooster went to Lei Cheung, but it also depends on when when blueprint or effect gets evaluated. The path you get might not be perfect, but should be more than good enough. Endlessly trying to optimize it will significantly increase computation time and the route gets updated on each jump/change.

**Comment by michelvaleferreira** [comment]
I see your point. If I have a powerplant blueprint pinned and only need the experimental, does it allow me to apply it at Felicity Farseer?

**Comment by jixxed** [comment]
yes, Remote Workshop option should come first in the list for blueprints. It can also route you to engineers for experimentals when you do not have a blueprint for it.
