### ISSUE TITLE
Request: check-mark completed Engineer Unlock steps.

### ISSUE THREAD

**Issue by SirWumpus** [jixxed/ed-odyssey-materials-helper#42]
Was going to ask for the ability to read back through old journals for new users of the Helper, because I was confused why the Helper was telling me I still needed 100ly in shuttles to start Domino Green.   Finally noticed that the completed steps appear as green in the engineer drop list.   Would be nice to show a green check-mark beside or over-strike text of each completed Objective for extra clarity.

**Comment by jixxed** [comment]
will be improved in the next release
![image](https://user-images.githubusercontent.com/14129491/128615859-2cbbc4e9-4fb7-463c-8c49-f614b21e5559.png)

**Comment by SirWumpus** [comment]
No.  You misunderstand.  I mean in the description screen, not the droplist, that already made sense.  When you select a step it should reflect the state in the text  (done, well maybe, eye glances, didn't do homework).

**Comment by jixxed** [comment]
I cannot track the individual steps so this would be an issue when there is more than 1 objective. What has been changed is that the selected item now shows as green(before white) and I added the checkmark, because I liked the idea. with this it should be more than clear enough this engineer unlock is completed.

**Comment by jixxed** [comment]
added in 1.39
