### ISSUE TITLE
Suggestion: Different audio cues

### ISSUE THREAD

**Issue by MalicT** [jixxed/ed-odyssey-materials-helper#79]
Viewer made me aware of this program yesterday and am enjoying using it.

However, I play in VR, and I cannot see the overlay during normal play.

One of my mods made a compass program with a customized feature that uses audio beeps changing from left to right to help me point in a direction, and I use audio cues with Voice attack to have good and bad sound cues.

Would there be a way to add different cues for needed, item, unneeded, and not needed, but good for bartering.

**Comment by jixxed** [comment]
Just watched your stream for a bit. Adding an optional notification for a wishlist item is a good idea, I will look into this. 
Items for bartering are not really relevant. Get a maverick suit and a backpack upgrade. Grab all assets (in the open lockers) and trade to the most valuable to compress when you hit the 1K limit. Goods (sealed lockers) are hard to fill up since a limited amount is relevant. Relevant data you usually always want to collect because you can always trade with other players or throw away later if space becomes an issue, instead of not collecting it at all.
the monetary value is negligible for all materials.

Another tip to quickly get the data or goods you need, is to take missions. Some missions are just a quick in and out and gives you up to 5 of the required data. even more if you have a good standing with one of the NPC mission givers at the station. There are also some good people over on the discord to give you tips on farming and crafting if you so desire.

**Comment by MalicT** [comment]
Yeah, it is the first time I have gotten to the point where I needed to barter items, so figuring that part out.  I have so much I need to get upgraded :)

**Comment by jixxed** [comment]
wishlist material pickup notification configuration added in 1.74
