### ISSUE TITLE
Need to be able to use on a separate computer

### ISSUE THREAD

**Issue by DawnTreader** [jixxed/ed-odyssey-materials-helper#82]
With the game taking up my screen flipping back and forth is a pain. It would be great if you would enable a way to login to the API and change the journal directory on a second computer without having to install and run the game on that computer.

**Comment by jixxed** [comment]
This is already possible if you make your journals accessible over the network to the other machine. complete API usage is not an option since it we can't query it continuously and it can run behind on your journals. You can login to the API under settings to to make fleetcarrier storage available to the app.
